version: "3"

services:
  # Tunnel into Cloudflare services
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    ports:
      - 8080:80/tcp
    volumes:
      - cloudflared:/root
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  # Provide HTTPS endpoints within the local network
  proxy:
    container_name: nginx/nginx
    restart: unless-stopped

  # Provide local DNS, ad-blocking, and ensure requests 
  # to Cloudflare go through tunnel
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "8080:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    environment:
      - ServerIP=10.0.0.3
      - DNS1='10.0.0.2#5054'
      - DNS2=''
      - IPv6=false
      - TZ=PST-7
      - DNSMASQ_LISTENING=all
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
volumes:
  pihole:
  cloudflared:
